"""Plot the average rewards of all models and envs."""

import pandas
from typing import Union, List
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
import json


class Records:
    def __init__(self, root_dir: str):
        """Load all records from the root directory.

        Directory structure:
        root_dir/
            reservoir_name/
                env_name/
                    seed/
                        0.monitor.csv
                        1.monitor.csv
                        ...

        CSV files are generated by gymnasium's Monitor wrapper.
        Structure of CSV files (example):
        #{"t_start": 1761958562.5481088, "env_id": "Acrobot-v1"}
        r, l, t
        ___, ___, ___
        ...
        """
        self.root_dir = root_dir
        self.records = (
            dict()
        )  # reservoir_name -> env_name -> seed -> list of DataFrames

        for reservoir_name in os.listdir(root_dir):
            res_path = os.path.join(root_dir, reservoir_name)
            if not os.path.isdir(res_path):
                continue
            self.records.setdefault(reservoir_name, {})
            for env_name in os.listdir(res_path):
                env_path = os.path.join(res_path, env_name)
                if not os.path.isdir(env_path):
                    continue
                self.records[reservoir_name].setdefault(env_name, {})
                for seed in os.listdir(env_path):
                    seed_path = os.path.join(env_path, seed)
                    seed_id = int(seed.split("_")[-1])
                    if not os.path.isdir(seed_path):
                        continue
                    monitor_files = glob.glob(os.path.join(seed_path, "*.monitor.csv"))
                    dfs = []
                    for csv_file in sorted(monitor_files):
                        with open(csv_file, "r") as f:
                            lines = f.readlines()
                        lines = [
                            line for line in lines if not line.lstrip().startswith("#")
                        ]
                        if not lines:
                            continue
                        # Remove potential blank lines at start/end
                        lines = [line for line in lines if line.strip()]
                        # DataFrame from csv string
                        import io

                        df = pandas.read_csv(io.StringIO("".join(lines)))
                        dfs.append(df)
                    self.records[reservoir_name][env_name][seed_id] = dfs

    def __getitem__(self, keys: Union[str, List[Union[str, int]]]) -> dict:
        """
        Allows indexing with [reservoir], [reservoir, env], or [reservoir, env, seed],
        or [reservoir, env, seed, episode].
        Returns dict or list accordingly.

        Examples:
        records['identity', 'Acrobot-v1', 0, 0]
        records['identity', 'Acrobot-v1', 0]
        records['identity', 'Acrobot-v1']
        records['identity']
        """
        if isinstance(keys, str):
            keys = [keys]
        node = self.records
        for key in keys:
            node = node[key]
        return node

    def __len__(self) -> int:
        """Returns the total number of seeds (runs) across all reservoirs and envs."""
        count = 0
        for res in self.records.values():
            for env in res.values():
                count += len(env)
        return count

    def __repr__(self) -> str:
        msg = f"<Records(root_dir={self.root_dir!r}, "
        n_res = len(self.records)
        n_envs = sum(len(res) for res in self.records.values())
        n_seeds = self.__len__()
        msg += f"{n_res} reservoirs, {n_envs} envs, {n_seeds} seeds)>"
        return msg


def average_rewards(records: List[pandas.DataFrame]) -> np.ndarray:
    if isinstance(records, dict):
        avg_reward = [average_rewards(r) for r in records.values()]
        # elements of avg_reward have different length
        max_len = max(len(r) for r in avg_reward)
        reward = np.array([0.0] * max_len)
        reward_sqr = np.array([0.0] * max_len)
        n_count = np.array([0.0] * max_len)
        for r in avg_reward:
            reward[: len(r)] += r
            reward_sqr[: len(r)] += r**2
            n_count[: len(r)] += 1

        avg = reward / n_count
        std = np.sqrt(reward_sqr / n_count - avg**2)
        return avg, std
    elif isinstance(records, list):
        return pandas.concat(records).groupby(level=0)["r"].mean().values


def _get_max_time(
    record: Union[
        dict[int, list[pandas.DataFrame]], list[pandas.DataFrame], pandas.DataFrame
    ],
) -> float:
    if isinstance(record, pandas.DataFrame):
        return float(record["t"].max())
    elif isinstance(record, list):
        return max([_get_max_time(r) for r in record])
    elif isinstance(record, dict):
        return max([_get_max_time(r) for r in record.values()])

    raise ValueError(f"Unknown record type: {type(record)}")


def bin_count_by_steps(
    rewards: np.ndarray, steps: np.ndarray, t_min: float, t_max: float, t_step: float, n: int
) -> list[float]:
    bin = [0] * n
    for r, s in zip(rewards, steps):
        idx = min(n - 1, int((s - t_min) // t_step))
        if bin[idx] == 0:
            bin[idx] = []
        bin[idx].append(r)

    # Use the first available bin to avoid leading NaNs
    first_value = np.nan
    for item in bin:
        if isinstance(item, list) and len(item) > 0:
            first_value = float(np.mean(item))
            break

    last_value = first_value
    for i in range(len(bin)):
        if isinstance(bin[i], list):
            bin[i] = float(np.mean(bin[i]))
            last_value = float(bin[i])
        else:
            bin[i] = float(last_value)
    return np.array(bin)


def average_rewards(
    record: dict[int, list[pandas.DataFrame]], n=10, reward_name="r", time_name="t"
):
    """
    record: dict[int, list[pandas.DataFrame]]
        seed -> list of DataFrames. Here, the list contains multiple DataFrames for the same
        seed in different parallel runs.
    """
    # Use cumulative timesteps (sum of episode lengths) instead of wall-clock time.
    t_min = 0
    t_max = 0
    for s in record.keys():
        n_envs = len(record[s])
        for r in record[s]:
            if r.empty:
                continue
            steps = r["l"].cumsum().iloc[-1] * n_envs
            t_max = max(t_max, float(steps))
    t_step = (t_max - t_min) / n if t_max > 0 else 1.0
    bins = []
    for s in record.keys():
        seed_bins = []
        n_envs = len(record[s])
        for r in record[s]:
            if r.empty:
                continue
            rewards = r[reward_name].to_numpy()
            steps = r["l"].cumsum().to_numpy() * n_envs
            seed_bins.append(bin_count_by_steps(rewards, steps, t_min, t_max, t_step, n))
        bins.append(np.mean(seed_bins, axis=0))

    return bins


if __name__ == "__main__":
    import argparse
    from collections import OrderedDict

    parser = argparse.ArgumentParser()
    parser.add_argument("--log_root", type=str, default="./results/log")
    parser.add_argument("--output_dir", type=str, default="./results/figures")
    parser.add_argument("--output_prefix", type=str, default="rewards")
    parser.add_argument(
        "--envs",
        nargs="+",
        default=[
            "CartPole-v1",
            "Acrobot-v1",
            "MountainCarContinuous-v0",
            "Pendulum-v1",
            "Reacher-v4",
            "Pusher-v4",
            "Swimmer-v4",
            "Hopper-v4",
            "HalfCheetah-v4",
            "HumanoidStandup-v4",
            "PointMaze",
            "finger-spin",
            "BankHeist-ram",
            "KungFuMaster-ram",
            "CrazyClimber-ram",
            "Kangaroo-ram",
        ],
    )
    parser.add_argument(
        "--reservoirs",
        nargs="+",
        default=[
            "identity_gradient",
            "mlp_gradient",
            "lorenzsystem_gradient",
            "tyson1999circlelock_gradient",
            "weimann2004circadianoscillator_gradient",
            "almeida2019circadianclock_gradient",
            "leloup1999circadianclock_gradient",
            "tyson1991cellcycle2var_gradient",
            "gardner1998cellcyclegoldbeter_gradient",
            "gerard2010cellcycle_gradient",
            "chickarmane2006stemcellswitch_gradient",
            "chickarmane2008nanoggata6_gradient",
            "zatorsky2006p53model4_gradient",
            "gardner2000toggleswitch_gradient",
            "liebal2012transcriptioninhibition_gradient",
            "markevich2004mapkdoublephosphorylation_gradient",
            "kholodenko2000mapkcascade_gradient",
        ],
    )
    parser.add_argument("--n_bins", type=int, default=10)
    parser.add_argument("--n_cols", type=int, default=3)
    args = parser.parse_args()

    records = Records(args.log_root)

    display_names = {
        "identity": "Linear",
        "mlp": "MLP",
        "lorenzsystem": "Lorenz",
        "tyson1999circlelock": "Tyson99",
        "markevich2004mapkdoublephosphorylation": "MAPK",
        "tyson1991cellcycle2var": "Tyson91",
        "weimann2004circadianoscillator": "Weimann04",
        "almeida2019circadianclock": "Almeida19",
        "zatorsky2006p53model4": "p53",
        "gardner2000toggleswitch": "Toggle",
        "liebal2012transcriptioninhibition": "Liebal12",
        "gerard2010cellcycle": "Gerard10",
        "chickarmane2006stemcellswitch": "StemCell",
        "gardner1998cellcyclegoldbeter": "Gardner98",
        "leloup1999circadianclock": "Leloup99",
        "chickarmane2008nanoggata6": "NanogGata6",
        "kholodenko2000mapkcascade": "MAPKcasc",
    }

    # Category-based color scheme: category -> {base_name: hex_color}
    CATEGORY_COLORS = OrderedDict([
        ("Control", OrderedDict([
            ("identity", "#636363"), ("mlp", "#969696"),
        ])),
        ("Baseline", OrderedDict([
            ("lorenzsystem", "#252525"),
        ])),
        ("Circadian", OrderedDict([
            ("tyson1999circlelock", "#08519c"),
            ("weimann2004circadianoscillator", "#2171b5"),
            ("almeida2019circadianclock", "#4292c6"),
            ("leloup1999circadianclock", "#6baed6"),
        ])),
        ("Cell Cycle", OrderedDict([
            ("tyson1991cellcycle2var", "#006d2c"),
            ("gardner1998cellcyclegoldbeter", "#238b45"),
            ("gerard2010cellcycle", "#41ab5d"),
        ])),
        ("Cell Fate", OrderedDict([
            ("chickarmane2006stemcellswitch", "#cb181d"),
            ("chickarmane2008nanoggata6", "#ef3b2c"),
        ])),
        ("p53", OrderedDict([
            ("zatorsky2006p53model4", "#7b2d8e"),
        ])),
        ("Synthetic", OrderedDict([
            ("gardner2000toggleswitch", "#e6550d"),
            ("liebal2012transcriptioninhibition", "#fd8d3c"),
        ])),
        ("Signaling", OrderedDict([
            ("markevich2004mapkdoublephosphorylation", "#006d6f"),
            ("kholodenko2000mapkcascade", "#17becf"),
        ])),
    ])

    # Build flat style lookup: base_name -> {color, ls, lw, cat}
    styles = {}
    for cat, members in CATEGORY_COLORS.items():
        for base, color in members.items():
            ls = "--" if cat == "Control" else "-"
            lw = 1.0 if cat in ("Control", "Baseline") else 0.7
            styles[base] = {"color": color, "ls": ls, "lw": lw, "cat": cat}

    # Match args.reservoirs (may have _gradient suffix) to styles, preserving category order
    models = OrderedDict()
    for cat, members in CATEGORY_COLORS.items():
        for base in members:
            for res in args.reservoirs:
                if res.replace("_gradient", "") == base:
                    models[res] = display_names.get(base, base)
                    styles[res] = styles[base]
                    break

    # Filter to envs that have at least some data
    available_envs = []
    for env in args.envs:
        for res in models:
            try:
                records[res, env]
                available_envs.append(env)
                break
            except KeyError:
                continue
    envs = OrderedDict((e, e) for e in available_envs)

    n_envs_total = len(envs)
    n_cols = args.n_cols
    n_rows = int(np.ceil(n_envs_total / n_cols)) if n_envs_total > 0 else 1

    # Paper textwidth ≈ 6.50 inches (469.75pt). Size figure to match.
    TEXTWIDTH = 6.5
    box_h = (TEXTWIDTH / n_cols) / 1.618
    row_h = box_h + 0.35  # box + title/xlabel/ticks overhead (tight)
    fig_h = n_rows * row_h + 0.45  # + legend only, no extra row gaps
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(TEXTWIDTH, fig_h))
    if n_rows * n_cols == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    for i, (env, env_name) in enumerate(envs.items()):
        ax = axes[i]
        ax.set_box_aspect(1 / 1.618)  # golden ratio for the axes box itself
        # Determine shared time axis from cumulative timesteps
        step_maxes = []
        for method in models:
            try:
                record = records[method, env]
            except KeyError:
                continue
            for s in record:
                n_runners = len(record[s])
                for r in record[s]:
                    if r.empty:
                        continue
                    step_maxes.append(float(r["l"].cumsum().iloc[-1] * n_runners))
        env_t_max = max(step_maxes) if step_maxes else 1.0
        t_step = env_t_max / args.n_bins if env_t_max > 0 else 1.0
        scale = 10 ** max(0, int(np.floor(np.log10(max(env_t_max, 1.0)))))
        x_axis = np.arange(args.n_bins) * t_step / scale

        for method, method_name in models.items():
            s = styles[method]
            try:
                bin_counts = average_rewards(records[method, env], n=args.n_bins)
            except KeyError:
                continue
            mean = np.quantile(bin_counts, 0.8, axis=0)
            p_high, p_low = np.percentile(bin_counts, [70, 90], axis=0)
            ax.plot(x_axis, mean, s["ls"], color=s["color"], linewidth=s["lw"])
            ax.fill_between(x_axis, p_low, p_high, alpha=0.10, color=s["color"])

        ax.set_xlabel(f"Timestep ($\\times 10^{{{int(np.log10(scale))}}}$)", fontsize=7, labelpad=1)
        if i % n_cols == 0:
            ax.set_ylabel("Reward", fontsize=7, labelpad=1)
        ax.set_title(env_name, fontsize=8, pad=2)
        ax.tick_params(labelsize=6, pad=1)
        ax.ticklabel_format(axis="y", style="sci", scilimits=(-3, 3), useMathText=True)
        if ax.yaxis.get_offset_text():
            ax.yaxis.get_offset_text().set_fontsize(5)

    # Hide unused subplots
    for i in range(n_envs_total, len(axes)):
        axes[i].set_visible(False)

    # Build bottom legend ordered by category (no category headers)
    legend_handles = []
    legend_labels = []
    for cat, members in CATEGORY_COLORS.items():
        for base, color in members.items():
            s = styles[base]
            name = display_names.get(base, base)
            legend_handles.append(
                plt.Line2D([0], [0], color=s["color"], linestyle=s["ls"], linewidth=max(s["lw"], 0.8))
            )
            legend_labels.append(name)

    fig.legend(
        legend_handles, legend_labels,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.02),
        fontsize=6,
        frameon=False,
        ncol=6,
        handlelength=2.0,
        columnspacing=1.0,
        handletextpad=0.5,
    )

    legend_frac = 0.45 / fig_h
    fig.tight_layout(rect=[0, legend_frac, 1, 1], h_pad=0.05, w_pad=0.15)
    os.makedirs(args.output_dir, exist_ok=True)
    fig.savefig(f"{args.output_dir}/{args.output_prefix}.pdf", bbox_inches="tight")
    fig.savefig(f"{args.output_dir}/{args.output_prefix}.png", bbox_inches="tight", dpi=300)
    plt.close()
